### ISSUE TITLE
client.guilds.get is not a function - Discord.js cache not supported

### ISSUE THREAD

**Issue by Androz2091** [WarHammer414/erela.js#10]
It throws the following error:
```
(node:34738) UnhandledPromiseRejectionWarning: TypeError: this.client.guilds.get is not a function
    at ErelaClient.sendWS (/Users/simon/Documents/GitHub/AtlantaBotv5/node_modules/erela.js/dist/lib/ErelaClient.js:218:42)
    at Map.spawn (/Users/simon/Documents/GitHub/AtlantaBotv5/node_modules/erela.js/dist/lib/stores/PlayerStore.js:34:20)
    at module.exports.execute (/Users/simon/Documents/GitHub/AtlantaBotv5/src/commands/Music/play.js:18:50)
    at Message.execute (/Users/simon/Documents/GitHub/AtlantaBotv5/src/events/message.js:161:21)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:34738) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:34738) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
when I try to spawn a player using the master branch of Discord.js. Discord.js now uses Managers and removed Datastores so we need to use `client.guilds.cache.get` now. Please fix this 🙏

**Comment by Strandxo** [comment]
Discord.js doesn't "now" use anything. The master branch is a development branch that you use at your own risk. The stable branch however is still supported with the package. We are attempting to find a convenient way to allow the use of master with the package. Until then you can fork and alter the code yourself :)

**Comment by Anish-Shobith** [comment]
I will make a pr for it, after school ✌️

**Comment by Androz2091** [comment]
It's what I did @Strandxo.

And what I wanted to say is "The **master** branch of Discord.js, which is a development branch, and which is supposed to be supported by the package now uses managers, whose aren't supported by this package.".
I'm sorry if I misspoke.

Nice @Anish-Shobith, thank you👍

**Comment by Anish-Shobith** [comment]
@Androz2091 just found that, erela.js already manages sending packets to the discord API. what if you call sendWS function and manage it yourself ? The work around i have found was just making a new branch and support for discord.js v12. or this one above .
I have not tested it. I am kinda busy with exams and stuff and can't be more on computer for time being, plus I don't use erela.js. I use lavalink. Let me know if this works out , if it doesn't then I will ask war aka Solaris (now) to make a new branch for the support of discord.js-v12.
```ts
import { ErelaClient, IPacket } from '../src/index';
import { Client } from 'discord.js';
const client = new Client();
class lavalinkClient extends ErelaClient {
    sendWS(data: IPacket) {
        const guild = client.guilds.cache.get(data.d.guild_id);
        if (guild) { 
           const { shard } = client.guilds.cache.get(guild.id);
            shard.send(data);
        }
    }
}
const lavalink = new lavalinkClient(client, []);
```
I have not tested this. Let me know if this work around helps out , and more thing i forgot to mention was , `Ipacket` interface is not exported. I was editing the code so i exported in my case, in you case just make a interface
```ts
export interface IPacket {
    op: number;
    d: any;
    s?: number;
    t?: string;
}
```

**Comment by Androz2091** [comment]
I tested this branch:
https://github.com/Anish-Shobith/erela.js/tree/v12-fix-build
And it didn't work, I need to edit this line to make it work.
```js
if (typeof this.client.guilds.get(data.d.guild_id) !== "function") {
```
⬇️ 
```js
if (typeof this.client.guilds.get !== "function") {
```

I also tested the code you sent above (to create a class that extends the ErelaClient one) and I had to use `this.client.guilds` instead of `client.guilds`. And it works!

**Comment by Anish-Shobith** [comment]
Thank you for testing it out. I will make a fix for it and ask war to make a public release for supporting v12 , if you check the development version , i guess he has used a better way to check v12 and v11 and i guess that should work a bit better than what i gave because its a bit lengthy.
```js
const guild = (this.client.guilds.get ? this.client.guilds : this.client.guilds.cache).get(data.d.guild_id);
```

**Comment by WarHammer414** [comment]
Unfortunately I don't have the source code for the NPM release and the master branch hasn't been updated with the latest code, you'll probably encounter more bugs with the master branch than the release on NPM. The development branch should be good to use if you build it yourself using the TypeScript compiler.

**Comment by Strandxo** [comment]
Just download the package from npm then you goose 😂😂😂😂

**Comment by WarHammer414** [comment]
> Just download the package from npm then you goose 😂😂😂😂

no u, my mind is half gone from using gradle, but I can do that

**Comment by Anish-Shobith** [comment]
Lmfao

**Comment by Androz2091** [comment]
Yes, that's what I did 2 days ago on my fork :smile:
https://github.com/Androz2091/erela.js/commit/20466355865e6327f7a465c0f8dfabf665ea81e5#diff-f568ea964ca83a683f3eca25fe73b67eR221

**Comment by WarHammer414** [comment]
This is fixed and more in the [development branch](https://github.com/WarHammer414/erela.js/tree/development). I'll push to NPM soon.
