### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by SerenModz21** [WarHammer414/erela.js#2]
When i just get my bot to the play the first time, how can i make it so both the enqueuing message and the now playing doesn't show. So like i can have it so just the now playing message shows and then the enqueuing message shows when you add another song to the queue. 

Hopefully this makes sense

**Comment by Strandxo** [comment]
Very easy. Check the queue size and go from there.

**Comment by SerenModz21** [comment]
How would i check the queue size?

**Comment by SerenModz21** [comment]
Thank You !
