### ISSUE TITLE
.get() not a function of PlayerStore which extends Collection according to docs

### ISSUE THREAD

**Issue by FracturX** [WarHammer414/erela.js#22]
![Screen Shot 2020-05-11 at 10 11 39 PM](https://user-images.githubusercontent.com/62032183/81632155-91b48500-93d7-11ea-874b-ce5b61460209.png)
![Screen Shot 2020-05-11 at 10 13 03 PM](https://user-images.githubusercontent.com/62032183/81632167-97aa6600-93d7-11ea-9383-112110315570.png)

Pretty self-explanatory. I'm using typescript with erela.js and am stumped on this issue which I'm pretty sure isn't of my own fault. Any help would be much appreciated.

**Comment by FracturX** [comment]
gonna add just in case that the error also appears when running tsc

**Comment by chroventer** [comment]
@FracturX, .get() method is not inherited from the Collection class which further extends Map.

**Comment by FracturX** [comment]
ya i made a temporarily fix and did PlayerStore extends Store<string, Player>

**Comment by WarHammer414** [comment]
That's my fault, I forgot to say PlayerStore extended Store in the typings, but for the next update the typings will be generated automatically and will always be proper, but I'm experiencing an issue with the generator so I haven't used it for the current release for erela.js yet.

**Comment by FracturX** [comment]
Thanks a bunch! :)

**Comment by chroventer** [comment]
Opened a pull-request!

**Comment by Anish-Shobith** [comment]
Will close the issue when the pr is merged!

**Comment by chroventer** [comment]
@FracturX, you can update to the latest version by running `npm install WarHammer414/erela.js`
