### ISSUE TITLE
Bug with pause method

### ISSUE THREAD

**Issue by Tetracyl** [WarHammer414/erela.js#27]
If you add a song to the queue, then pause the queue using the pause method, then add another song to the queue, erela.js will skip all songs in the queue and emit the trackStart event for each song in the queue. This might cause the bot to spam depending on how many songs are in the queue.

![image](https://user-images.githubusercontent.com/29833473/82162490-d027c500-9859-11ea-8724-6ce697afbc76.png)

**Comment by WarHammer414** [comment]
This seems to be fixed with the rewrite version with slight alteration where you play tracks.
```javascript
if (!player.playing && !player.paused && player.queue.length === 1) player.play()
```
If this seems to persist with rewrite then reopen this issue.

**Comment by HoaX7** [comment]
Hi, Im facing the same bug but not when you add songs to a queue, when you stop the player and then add songs again

**Comment by Solaris9** [comment]
Please create a new issue about what your experiencing.

**Comment by HoaX7** [comment]
sure but the solution commented on here doesn't work

**Comment by Solaris9** [comment]
Because this is a old bug that is fixed about pausing, you said yours was stopping the player.
