### ISSUE TITLE
Bug with loop and pause method

### ISSUE THREAD

**Issue by Tetracyl** [WarHammer414/erela.js#28]
This bug is linked to issue #27 . If you add a song to the queue, then loop the queue, then pause the queue, then add another song to the queue, erela.js will skip through everything in the queue. And since the song is looped, it will try to skip the same song over and over again, resulting in the trackStart event being emitted numerous times in the span of a couple of seconds.

![image](https://user-images.githubusercontent.com/29833473/82162569-62c86400-985a-11ea-9f6a-d4a39dfa20a9.png)

**Comment by WarHammer414** [comment]
This seems to be fixed with the rewrite version with slight alteration where you play tracks.
```javascript
if (!player.playing && !player.paused && player.queue.length === 1) player.play()
```
If this seems to persist with rewrite then reopen this issue.
