### ISSUE TITLE
Search method sometimes will not return any results

### ISSUE THREAD

**Issue by ShinobisSneaky** [WarHammer414/erela.js#32]
Every now and again when using the search method it will return "No tracks were found." Yet if I search the same thing another 1 - 3 times it will give me results. It seems to be very random as when I try to recreate the issue I get varied results.

**Comment by ShinobisSneaky** [comment]
It appears to get worse the longer the bot is online as well

**Comment by WarHammer414** [comment]
There's two reasons for this, one is Lavalink not actually finding any results, and two is how Erela handles it in the [`ErelaClient#search()`](https://github.com/WarHammer414/erela.js/blob/master/src/lib/ErelaClient.ts#L364) method, it checks if there are not tracks, but if there is an error it will return both the error and tracks, Erela sees that there is no tracks and throws that error. This has been fixed on rewrite which will have every [load type](https://github.com/WarHammer414/erela.js/blob/rewrite/src/structures/Utils.ts#L240) Lavalink sends and one be in the result which you can use to check if the load failed, if there was no tracks, etc. Rewrite will release soon as it is finished, every improvement so far as been added and all of the code has been tested, as well as the docs will be automatically updated whenever a new version is released.
