### ISSUE TITLE
queueRepeat doesn't work (rewrite)

### ISSUE THREAD

**Issue by Tetracyl** [WarHammer414/erela.js#36]
I'm doing setQueueRepeat(true) but it doesn't loop the queue at all.

Here I play two songs, loop the queue, check if the queue is looped, then I skip both songs and the queue ends...

![image](https://user-images.githubusercontent.com/29833473/86282437-14fe8580-bb94-11ea-9f86-aacebaafc309.png)
![image](https://user-images.githubusercontent.com/29833473/86282452-1d56c080-bb94-11ea-824b-0ee1cd582a15.png)

**Comment by chroventer** [comment]
@Tetracyl I and some of the contributors are unable to reproduce this issue. Can you provide reproducible code to replicate this issue?
