### ISSUE TITLE
Filter issues 

### ISSUE THREAD

**Issue by blaise69** [WarHammer414/erela.js#39]
It seems when ever i set filters it sounds like earrape

**Comment by WarHammer414** [comment]
Erela.js doesn't have any other filters, only equalizer filter currently, if it sounds bad then you're probably using it wrong, join the [support server](https://discord.gg/D6FXw55) to receive support as issues are for bugs with the package.

**Comment by blaise69** [comment]
okay I have been having this issue for some time but i didn't know what to do
