### ISSUE TITLE
Add playlist support and a skip method

### ISSUE THREAD

**Issue by ShimaHaucksDeveloper** [WarHammer414/erela.js#6]

**Comment by Strandxo** [comment]
Both of these already exist?

**Comment by ShimaHaucksDeveloper** [comment]
skip part doesn't exist, i tried to make one and it didn't work with playlist, it issues track start event several times

**Comment by WarHammer414** [comment]
skip is basically Player#stop() and it does work with playlists, you just have to manually iterate over the playlist SearchResult gives and add it to the queue, i should make a shortcut by just adding the playlist itself, and a final note, it also depends on lavalink and youtube, sometimes they might not work and a playlist may be unavailable
