### ISSUE TITLE
how can i get live duration of song

### ISSUE THREAD

**Issue by RootAndroid58** [WarHammer414/erela.js#8]
Normally to get the duration of song is 
```
const player = client.music.players.get(message.guild.id);
const { title, author, duration, thumbnail } = player.queue[0];
```
this line will simply give me total  duration of current song but how can i get current duration of the song 
example 1:12/4:24 here what i want to get is 1:12 which i will edit the last massage and edit the massage every 5 sec

**Comment by Anish-Shobith** [comment]
You simply can't get the duration of live song getting played, you might never know when the stream is gonna end , all you can do is (if possible), get the time escaped in that stream and convert it into total time. but i am not sure if that information is given.

**Comment by RootAndroid58** [comment]
then i have a bot called Jmusic bot they made it possible  
here is their source code 
https://github.com/jagrosh/MusicBot

**Comment by RootAndroid58** [comment]
> You simply can't get the duration of live song getting played, you might never know when the stream is gonna end , all you can do is (if possible), get the time escaped in that stream and convert it into total time. but i am not sure if that information is given.

also as far as live stream goes no one asked for end duration just the time the bot started playing

**Comment by RootAndroid58** [comment]
i got it
